# Generated by Django 3.0.5 on 2020-04-30 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('repId', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
