# Generated by Django 3.0.5 on 2020-04-30 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseAPI', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Repository',
        ),
    ]
