# Generated by Django 3.0.5 on 2020-04-30 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseAPI', '0003_repository'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='repId',
            new_name='repid',
        ),
    ]
