# Generated by Django 3.0.5 on 2020-04-30 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseAPI', '0004_auto_20200430_1006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Repository',
        ),
    ]
