# Generated by Django 3.0.5 on 2020-04-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseAPI', '0005_delete_repository'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('repid', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
